name = "OneDim-QM-NI"
version = "1.1.0"

license = "GNU General Public License v3.0"
author = "Álvaro R. Puente-Uriona"
maintainer = "alvaro.ruiz@ehu.eus"
copyright = "Copyright 2025, Álvaro R. Puente-Uriona"

[library]
source-dir="src"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["blas", "lapack"]

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
openmp = "*"
